# Generated by Django 4.0 on 2022-01-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.IntegerField(max_length=4),
        ),
    ]
